name: CI

on:
  push:
    branches:
      - dev
  pull_request: ~

env:
  CACHE_VERSION: 1
  DEFAULT_PYTHON: 3.8
  PRE_COMMIT_HOME: ~/.cache/pre-commit

jobs:
  base:
    name: Setup base for CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y \
          gcc \
          libatlas3-base \
          portaudio19-dev \
          python3-pip
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        id: python
        uses: actions/setup-python@v2.2.1
        with:
            python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Restore base Python virtual environment
        id: cache-venv
        uses: actions/cache@v2
        with:
          path: venv
          key: >-
            ${{ env.CACHE_VERSION }}-${{ runner.os }}-base-venv-${{
            steps.python.outputs.python-version }}-${{
            hashFiles('requirements.txt') }}-${{
            hashFiles('requirements-dev.txt') }}
          restore-keys: |
            ${{ env.CACHE_VERSION }}-${{ runner.os }}-base-venv-${{ steps.python.outputs.python-version }}-${{hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}-
            ${{ env.CACHE_VERSION }}-${{ runner.os }}-base-venv-${{ steps.python.outputs.python-version }}-${{hashFiles('requirements.txt') }}
            ${{ env.CACHE_VERSION }}-${{ runner.os }}-base-venv-${{ steps.python.outputs.python-version }}-
      - name: Create Python virtual environment
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -U pip setuptools wheel
          pip install -r requirements.txt -r requirements-dev.txt
      - name: Restore pre-commit environment from cache-name
        id: cache-precommit
        uses: actions/cache@v2
        with:
          path: ${{ env.PRE_COMMIT_HOME }}
          key: |
            ${{ env.CACHE_VERSION }}-${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ env.CACHE_VERSION }}-${{ runner.os }}-pre-commit-
      - name: Install pre-commit dependencies
        if: steps.cache-precommit.outputs.cache-hit != 'true'
        run: |
          . venv/bin/activate
          pre-commit install-hooks
      - name: Run black
        run: |
          pre-commit run --hook-stage manual black --all-files --show-diff-on-failure
      - name: Run flake8
        run: |
          pre-commit run --hook-stage manual flake8 --all-files
      - name: Run isort
        run: |
          pre-commit run --hook-stage manual isort --all-files --show-diff-on-failure
