name: Test sed replace for sentry config

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  test-sed:
    name: Test sed replace for sentry config
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v2
      - name: Setup sentry config
        shell: bash
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
        run: |
          echo "$SENTRY_DSN"
          sed -i 's,SENTRY-DSN,'"$SENTRY_DSN"',g' ./ledfx/sentry_config.py
      - name: Test secret
        run: |
          cat ./ledfx/sentry_config.py
